<?php
require_once "../includes/auth.php";
protegerRuta();
soloAdmin();
require_once "../config/conexion.php";
$productos = mysqli_query($conexion, "SELECT p.*, c.nombre_categoria FROM producto p INNER JOIN categoria c ON p.id_categoria=c.id_categoria WHERE p.stock <= 5 AND p.estado='activo' ORDER BY p.stock ASC");
$total_bajo = mysqli_fetch_assoc(mysqli_query($conexion, "SELECT COUNT(*) total FROM producto WHERE stock <= 5 AND estado='activo'"))['total'];
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Stock</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/estilos.css"></head><body class="admin-body"><nav class="navbar navbar-dark admin-navbar sticky-top"><div class="container-fluid px-4"><a class="navbar-brand brand-logo" href="dashboard.php">PapuStore Admin</a><div class="d-flex gap-2"><a href="../index.php" class="btn btn-outline-light btn-sm"><i class="bi bi-house"></i> Tienda</a><a href="../logout.php" class="btn btn-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Salir</a></div></div></nav><div class="admin-shell"><aside class="admin-sidebar"><div class="menu-title">Panel</div><a class="admin-link " href="dashboard.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="admin-link " href="productos.php"><i class="bi bi-phone"></i> Productos</a><a class="admin-link " href="categorias.php"><i class="bi bi-tags"></i> Categorias</a><a class="admin-link active" href="stock.php"><i class="bi bi-box-seam"></i> Stock</a><a class="admin-link " href="ventas.php"><i class="bi bi-receipt"></i> Ventas</a><a class="admin-link " href="usuarios.php"><i class="bi bi-people"></i> Usuarios</a><div class="menu-title">Seguridad</div><div class="mini-badge"><i class="bi bi-shield-check"></i> Rutas protegidas</div><div class="mini-badge"><i class="bi bi-lock"></i> Rol admin</div></aside><main class="admin-content">
<section class="page-hero"><div class="row align-items-center"><div class="col-lg-8"><h1 class="fw-bold mb-1">Control de stock</h1><p class="mb-0 text-white-50">Detecta productos criticos y actualiza inventario antes de vender.</p></div><div class="col-lg-4 text-lg-end"><span class="mini-badge"><i class="bi bi-exclamation-triangle"></i> <?php echo $total_bajo; ?> en alerta</span></div></div></section>
<div class="card"><div class="card-body"><h4 class="mb-3">Productos con stock bajo</h4><div class="table-responsive"><table class="table table-hover align-middle"><tr><th>Producto</th><th>Categoria</th><th>Marca</th><th>Stock</th><th>Accion</th></tr><?php $hay=false; while($p=mysqli_fetch_assoc($productos)){ $hay=true; ?><tr><td class="fw-bold"><?php echo e($p['nombre']); ?></td><td><?php echo e($p['nombre_categoria']); ?></td><td><?php echo e($p['marca']); ?></td><td><span class="badge bg-danger"><?php echo $p['stock']; ?></span></td><td><a href="producto_editar.php?id=<?php echo $p['id_producto']; ?>" class="btn btn-warning btn-sm"><i class="bi bi-pencil"></i> Actualizar</a></td></tr><?php } ?><?php if(!$hay){ ?><tr><td colspan="5" class="text-center text-muted py-4">No hay productos con stock bajo.</td></tr><?php } ?></table></div></div></div>
</main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script></body></html>