<?php
require_once "../includes/auth.php";
protegerRuta();
soloAdmin();
require_once "../config/conexion.php";
$usuarios = mysqli_query($conexion, "SELECT id_usuario,nombre,correo,rol,estado_2fa,fecha_registro FROM usuario ORDER BY id_usuario DESC");
$total_admin = mysqli_fetch_assoc(mysqli_query($conexion, "SELECT COUNT(*) total FROM usuario WHERE rol='admin'"))['total'];
$total_cliente = mysqli_fetch_assoc(mysqli_query($conexion, "SELECT COUNT(*) total FROM usuario WHERE rol='cliente'"))['total'];
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Usuarios</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/estilos.css"></head><body class="admin-body"><nav class="navbar navbar-dark admin-navbar sticky-top"><div class="container-fluid px-4"><a class="navbar-brand brand-logo" href="dashboard.php">PapuStore Admin</a><div class="d-flex gap-2"><a href="../index.php" class="btn btn-outline-light btn-sm"><i class="bi bi-house"></i> Tienda</a><a href="../logout.php" class="btn btn-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Salir</a></div></div></nav><div class="admin-shell"><aside class="admin-sidebar"><div class="menu-title">Panel</div><a class="admin-link " href="dashboard.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="admin-link " href="productos.php"><i class="bi bi-phone"></i> Productos</a><a class="admin-link " href="categorias.php"><i class="bi bi-tags"></i> Categorias</a><a class="admin-link " href="stock.php"><i class="bi bi-box-seam"></i> Stock</a><a class="admin-link " href="ventas.php"><i class="bi bi-receipt"></i> Ventas</a><a class="admin-link active" href="usuarios.php"><i class="bi bi-people"></i> Usuarios</a><div class="menu-title">Seguridad</div><div class="mini-badge"><i class="bi bi-shield-check"></i> Rutas protegidas</div><div class="mini-badge"><i class="bi bi-lock"></i> Rol admin</div></aside><main class="admin-content">
<section class="page-hero"><h1 class="fw-bold mb-1">Usuarios registrados</h1><p class="mb-0 text-white-50">Consulta cuentas, roles y estado de verificacion 2FA.</p></section>
<div class="row g-4 mb-4"><div class="col-md-6"><div class="metric-card metric-dark"><span>Administradores</span><h2><?php echo $total_admin; ?></h2></div></div><div class="col-md-6"><div class="metric-card metric-purple"><span>Clientes</span><h2><?php echo $total_cliente; ?></h2></div></div></div>
<div class="card"><div class="card-body"><h4 class="mb-3">Listado de usuarios</h4><div class="table-responsive"><table class="table table-hover align-middle"><tr><th>ID</th><th>Nombre</th><th>Correo</th><th>Rol</th><th>2FA</th><th>Fecha</th></tr><?php while($u=mysqli_fetch_assoc($usuarios)){ ?><tr><td class="fw-bold">#<?php echo $u['id_usuario']; ?></td><td><?php echo e($u['nombre']); ?></td><td><?php echo e($u['correo']); ?></td><td><span class="badge bg-<?php echo $u['rol']==='admin'?'dark':'primary'; ?>"><?php echo e($u['rol']); ?></span></td><td><span class="badge bg-<?php echo $u['estado_2fa'] ? 'success' : 'warning'; ?>"><?php echo $u['estado_2fa'] ? 'Verificado' : 'Pendiente'; ?></span></td><td><?php echo e($u['fecha_registro']); ?></td></tr><?php } ?></table></div></div></div>
</main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script></body></html>