<?php
require_once "../includes/auth.php";
protegerRuta();
soloAdmin();
require_once "../config/conexion.php";
$ventas = mysqli_query($conexion, "SELECT v.*, u.nombre, u.correo FROM venta v INNER JOIN usuario u ON v.id_usuario=u.id_usuario ORDER BY v.id_venta DESC");
$total_ventas = mysqli_fetch_assoc(mysqli_query($conexion, "SELECT COUNT(*) total FROM venta"))['total'];
$total_ingresos = mysqli_fetch_assoc(mysqli_query($conexion, "SELECT IFNULL(SUM(total),0) total FROM venta WHERE estado_venta<>'cancelado'"))['total'];
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Ventas</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/estilos.css"></head><body class="admin-body"><nav class="navbar navbar-dark admin-navbar sticky-top"><div class="container-fluid px-4"><a class="navbar-brand brand-logo" href="dashboard.php">PapuStore Admin</a><div class="d-flex gap-2"><a href="../index.php" class="btn btn-outline-light btn-sm"><i class="bi bi-house"></i> Tienda</a><a href="../logout.php" class="btn btn-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Salir</a></div></div></nav><div class="admin-shell"><aside class="admin-sidebar"><div class="menu-title">Panel</div><a class="admin-link " href="dashboard.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="admin-link " href="productos.php"><i class="bi bi-phone"></i> Productos</a><a class="admin-link " href="categorias.php"><i class="bi bi-tags"></i> Categorias</a><a class="admin-link " href="stock.php"><i class="bi bi-box-seam"></i> Stock</a><a class="admin-link active" href="ventas.php"><i class="bi bi-receipt"></i> Ventas</a><a class="admin-link " href="usuarios.php"><i class="bi bi-people"></i> Usuarios</a><div class="menu-title">Seguridad</div><div class="mini-badge"><i class="bi bi-shield-check"></i> Rutas protegidas</div><div class="mini-badge"><i class="bi bi-lock"></i> Rol admin</div></aside><main class="admin-content">
<section class="page-hero"><div class="row align-items-center"><div class="col-lg-8"><h1 class="fw-bold mb-1">Registro de ventas</h1><p class="mb-0 text-white-50">Administra compras, estados y seguimiento de pedidos.</p></div><div class="col-lg-4 text-lg-end"><span class="mini-badge">Bs <?php echo number_format($total_ingresos,2); ?> registrados</span></div></div></section>
<div class="row g-4 mb-4"><div class="col-md-6"><div class="metric-card metric-blue"><span>Total ventas</span><h2><?php echo $total_ventas; ?></h2></div></div><div class="col-md-6"><div class="metric-card metric-green"><span>Ingresos</span><h2>Bs <?php echo number_format($total_ingresos,2); ?></h2></div></div></div>
<div class="card"><div class="card-body"><h4 class="mb-3">Ventas realizadas</h4><div class="table-responsive"><table class="table table-hover align-middle"><tr><th>ID</th><th>Cliente</th><th>Fecha</th><th>Total</th><th>Estado</th><th>Cambiar estado</th></tr><?php $hay=false; while($v=mysqli_fetch_assoc($ventas)){ $hay=true; ?><tr><td class="fw-bold">#<?php echo $v['id_venta']; ?></td><td><?php echo e($v['nombre']); ?><br><small class="text-muted"><?php echo e($v['correo']); ?></small></td><td><?php echo e($v['fecha']); ?></td><td class="fw-bold">Bs <?php echo number_format($v['total'],2); ?></td><td><span class="badge bg-<?php echo $v['estado_venta']==='pagado'?'success':($v['estado_venta']==='cancelado'?'danger':'warning'); ?>"><?php echo e($v['estado_venta']); ?></span></td><td><form method="POST" action="cambiar_estado_venta.php" class="d-flex gap-2"><input type="hidden" name="id_venta" value="<?php echo $v['id_venta']; ?>"><select name="estado_venta" class="form-select form-select-sm"><option value="pendiente" <?php echo $v['estado_venta']==='pendiente'?'selected':''; ?>>pendiente</option><option value="pagado" <?php echo $v['estado_venta']==='pagado'?'selected':''; ?>>pagado</option><option value="cancelado" <?php echo $v['estado_venta']==='cancelado'?'selected':''; ?>>cancelado</option></select><button class="btn btn-primary btn-sm">Guardar</button></form></td></tr><?php } ?><?php if(!$hay){ ?><tr><td colspan="6" class="text-center text-muted py-4">No hay ventas registradas.</td></tr><?php } ?></table></div></div></div>
</main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script></body></html>