<?php
require_once "../includes/auth.php";
protegerRuta();
soloCliente();
require_once "../config/conexion.php";
$id_usuario = $_SESSION['id_usuario'];
$stmt = mysqli_prepare($conexion, "SELECT p.*, c.nombre_categoria FROM favorito f INNER JOIN producto p ON f.id_producto=p.id_producto INNER JOIN categoria c ON p.id_categoria=c.id_categoria WHERE f.id_usuario=? ORDER BY f.fecha DESC");
mysqli_stmt_bind_param($stmt, "i", $id_usuario);
mysqli_stmt_execute($stmt);
$favoritos = mysqli_stmt_get_result($stmt);
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Favoritos</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/estilos.css"></head><body><nav class="navbar navbar-expand-lg navbar-dark nav-glass sticky-top"><div class="container"><a class="navbar-brand brand-logo" href="inicio.php">PapuStore</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#menuCliente"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="menuCliente"><div class="ms-auto d-flex flex-wrap gap-2 mt-3 mt-lg-0"><a href="inicio.php" class="btn btn-outline-light btn-sm"><i class="bi bi-shop"></i> Tienda</a><a href="favoritos.php" class="btn btn-outline-light btn-sm"><i class="bi bi-heart"></i> Favoritos</a><a href="historial.php" class="btn btn-outline-light btn-sm"><i class="bi bi-clock-history"></i> Historial</a><a href="../logout.php" class="btn btn-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Salir</a></div></div></div></nav>
<div class="container my-5"><section class="client-hero mb-5"><h1 class="fw-bold mb-2">Mis favoritos</h1><p class="mb-0 text-white-50">Productos guardados para revisar y comprar despues.</p></section><div class="row g-4"><?php $hay=false; while($p=mysqli_fetch_assoc($favoritos)){ $hay=true; ?><div class="col-md-6 col-xl-4"><div class="product-card"><img class="product-img" src="<?php echo e(imagenProducto($p['imagen'], '../')); ?>"><div class="card-body d-flex flex-column"><span class="badge badge-soft align-self-start mb-3"><?php echo e($p['nombre_categoria']); ?></span><h5><?php echo e($p['nombre']); ?></h5><p class="flex-grow-1"><?php echo e($p['descripcion']); ?></p><div class="price mb-3">Bs <?php echo number_format($p['precio'],2); ?></div><div class="d-grid gap-2 mt-auto"><a href="ver_producto.php?id=<?php echo (int)$p['id_producto']; ?>" class="btn btn-primary">Ver producto</a><a href="agregar_carrito.php?id=<?php echo (int)$p['id_producto']; ?>" class="btn btn-dark">Agregar carrito</a><a href="eliminar_favorito.php?id=<?php echo (int)$p['id_producto']; ?>" class="btn btn-outline-danger">Eliminar favorito</a></div></div></div></div><?php } ?><?php if(!$hay){ ?><div class="col-12"><div class="empty-state"><div class="feature-icon mx-auto"><i class="bi bi-heart"></i></div><h4>No tienes favoritos todavia</h4><p class="text-muted">Guarda productos desde la tienda para encontrarlos rapido.</p><a href="inicio.php" class="btn btn-primary">Ir a la tienda</a></div></div><?php } ?></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script><script src="../assets/js/script.js"></script></body></html>