<?php
require_once "../includes/auth.php";
protegerRuta();
soloCliente();
require_once "../config/conexion.php";
$id = (int)($_GET['id'] ?? 0);
$stmt = mysqli_prepare($conexion, "SELECT p.*, c.nombre_categoria FROM producto p INNER JOIN categoria c ON p.id_categoria=c.id_categoria WHERE p.id_producto=? AND p.estado='activo'");
mysqli_stmt_bind_param($stmt, "i", $id);
mysqli_stmt_execute($stmt);
$p = mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));
if (!$p) { header("Location: inicio.php"); exit(); }
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Detalle</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/estilos.css"></head><body><nav class="navbar navbar-expand-lg navbar-dark nav-glass sticky-top"><div class="container"><a class="navbar-brand brand-logo" href="inicio.php">PapuStore</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#menuCliente"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="menuCliente"><div class="ms-auto d-flex flex-wrap gap-2 mt-3 mt-lg-0"><a href="inicio.php" class="btn btn-outline-light btn-sm"><i class="bi bi-shop"></i> Tienda</a><a href="favoritos.php" class="btn btn-outline-light btn-sm"><i class="bi bi-heart"></i> Favoritos</a><a href="historial.php" class="btn btn-outline-light btn-sm"><i class="bi bi-clock-history"></i> Historial</a><a href="../logout.php" class="btn btn-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Salir</a></div></div></div></nav>
<div class="container my-5"><div class="card"><div class="card-body p-4 p-lg-5"><div class="row g-5 align-items-center"><div class="col-lg-5"><img class="product-img-lg" src="<?php echo e(imagenProducto($p['imagen'], '../')); ?>"></div><div class="col-lg-7"><span class="badge badge-soft mb-3"><?php echo e($p['nombre_categoria']); ?></span><h1 class="display-5 fw-bold"><?php echo e($p['nombre']); ?></h1><p class="lead text-muted"><?php echo e($p['descripcion']); ?></p><div class="row g-3 my-3"><div class="col-sm-6"><div class="category-pill"><strong>Marca</strong><h4><?php echo e($p['marca']); ?></h4></div></div><div class="col-sm-6"><div class="category-pill"><strong>Stock</strong><h4><?php echo $p['stock']; ?> unidades</h4></div></div></div><div class="price mb-4">Bs <?php echo number_format($p['precio'],2); ?></div><div class="d-flex flex-wrap gap-2"><a href="agregar_carrito.php?id=<?php echo $p['id_producto']; ?>" class="btn btn-dark"><i class="bi bi-cart-plus me-2"></i>Agregar carrito</a><a href="agregar_favorito.php?id=<?php echo $p['id_producto']; ?>" class="btn btn-outline-danger"><i class="bi bi-heart me-2"></i>Favorito</a><a href="inicio.php" class="btn btn-outline-primary"><i class="bi bi-arrow-left me-2"></i>Volver</a></div></div></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script><script src="../assets/js/script.js"></script></body></html>